<?php
declare(strict_types=1);
$this->headTitle('Unofficial site');
?>
<h1>Darklord MUD Unofficial Info site</h1>

<p>
    Hey folks, thought I'd throw up a quick site trying to collate all the (sometimes useful) information we have about
    Darklord to help others.
</p>

<h2>About Darklord</h2>

<p>
    Darklord is a MUD started by Mogwai and Foriz, a long time ago. In around 2004, the MUD went offline for several
    years. Now, Darklord is back!
</p>

<p>
    You can connect using either a basic telnet client, or preferably a dedicated MUD client to: darklordmud.duckdns.org:5000
</p>

<h2>Links</h2>

<ul>
    <li><a href="https://twitter.com/Darklord_MUD">@Darklord_MUD</a> on Twitter (though not very active...)</li>
    <li><a href="https://www.facebook.com/groups/1971833113088195">Unofficial Facebook group</li>
    <li><a href="https://www.topmudsites.com/vote-Darklord.html">Vote for Darklord</a> on Top MUD Sites</li>
</ul>
