<?php
declare(strict_types=1);
$this->headTitle('Miscellaneous information');
?>
<h1>Misc stuff</h1>

<h2>Skill levels</h2>

<table>
    <tr>
        <td>
            <h4>Major levels</h4>
            <ul>
                <li>Horrible</li>
                <li>Terrible</li>
                <li>Awful</li>
                <li>Bad</li>
                <li>Not so bad</li>
                <li>Poor</li>
                <li>Fair</li>
                <li>Somewhat good</li>
                <li>Almost good</li>
                <li>Good</li>
                <li>Very good</li>
                <li>Extremely good</li>
                <li>Excellent</li>
                <li>Awesome</li>
                <li>Dangerous</li>
                <li>Lethal</li>
                <li>Expert</li>
                <li>Masterly</li>
                <li>Superior</li>
                <li>Almost Godly</li>
                <li>Godly</li>
            </ul>
        </td>
        <td>
            <h4>Minor levels</h4>
            <ul>
                <li>Nothing</li>
                <li>Close to nothing</li>
                <li>Very little</li>
                <li>Some</li>
                <li>Almost half</li>
                <li>Half</li>
                <li>More than half</li>
                <li>Alot</li>
                <li>Very much</li>
                <li>Almost all</li>
            </ul>
        </td>
    </tr>
</table>


<h2>Levels of drunkenness</h2>

<p>In order:</p>

<ul>
    <li>You are sober</li>
    <li>You are slightly buzzed</li>
    <li>You are buzzed</li>
    <li>You are heavily buzzed</li>
    <li>You are a bit tipsy</li>
    <li>You are tipsy</li>
    <li>You are somewhat drunk</li>
    <li>You are somewhat intoxicated</li>
    <li>You are drunk</li>
    <li>You are intoxicated</li>
    <li>You’ve had enough to drink</li>
    <li>You are wasted</li>
    <li>You are very drunk</li>
    <li>You are shit-faced</li>
    <li>You are sloppy drunk</li>
    <li>You are so drunk, even your pet dog looks cute</li>
    <li>You surface from the bottle only to get some air</li>
    <li>You have alcohol poisoning</li>
</ul>

<p>At this point, you will fall over and not be able to drink any more: “You can’t seem to get close enough to your mouth.”</p>

<p>You “get drunk” much faster than you “sober up”, so whilst drinking from sober, you’ll notice some stages are skipped.</p>
