<?php
declare(strict_types=1);
$this->headTitle('Darklord MUD');
?>
<table>
    <thead>
    <tr>
        <th>Zone</th>
        <th>Author</th>
        <th>Est. Levels</th>
        <th>Directions</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>Limbo</td>
        <td>DikuMud</td>
        <td>Idle</td>
        <td>..</td>
    </tr>
    <tr>
        <td>Tristeza Forgotten</td>
        <td>Mogwai of Darklord</td>
        <td>Hard 30+</td>
        <td>..</td>
    </tr>
    <tr>
        <td>Eastern Forest</td>
        <td>Mogwai of Darklord</td>
        <td>Hard 30+</td>
        <td>..</td>
    </tr>
    <tr>
        <td>Thistledown</td>
        <td>Mogwai of Darklord</td>
        <td>Hard</td>
        <td>n;n;n;n;n;n;n;n;n;n;n;n;n;n;w;n;w;w;n;n;e;n;n;n;n;n;n;n;n</td>
    </tr>
    <tr>
        <td>Dragonia</td>
        <td>Mogwai of Darklord</td>
        <td>Varies</td>
        <td>..</td>
    </tr>
    <tr>
        <td>Lakeside Park</td>
        <td>Mogwai of Darklord</td>
        <td>Very Easy 1+</td>
        <td>..</td>
    </tr>
    <tr>
        <td>Temple of Syrinx</td>
        <td>Mogwai of Darklord</td>
        <td>Very Hard 35+</td>
        <td>..</td>
    </tr>
    <tr>
        <td>Thonia</td>
        <td>Mogwai of Darklord</td>
        <td>Hard</td>
        <td>..</td>
    </tr>
    <tr>
        <td>Oestgaard</td>
        <td>Foriz of Darklord</td>
        <td>Hard</td>
        <td>..</td>
    </tr>
    <tr>
        <td>Forgotten Fortress</td>
        <td>Foriz of Darklord</td>
        <td>Medium 25+</td>
        <td>..</td>
    </tr>
    <tr>
        <td>Sorcerer’s Isle</td>
        <td>Milamber of Darklord</td>
        <td>Easy 10+</td>
        <td>..</td>
    </tr>
    <tr>
        <td>Stonehenge</td>
        <td>Chronos of Darklord</td>
        <td>..</td>
        <td>..</td>
    </tr>
    <tr>
        <td>Highlands</td>
        <td>Mogwai of Darklord</td>
        <td>..</td>
        <td>..</td>
    </tr>
    <tr>
        <td>Dantes’ Limbo</td>
        <td>Addler &amp; Jarnot of Darklord</td>
        <td>Hard 30+</td>
        <td>..</td>
    </tr>
    <tr>
        <td>Valley of War</td>
        <td>Loretian, mortal of Darklord</td>
        <td>Level 8+</td>
        <td>..</td>
    </tr>
    <tr>
        <td>God Complex</td>
        <td>CircleMUD, modified by Datalore of Darklord</td>
        <td>..</td>
        <td>..</td>
    </tr>
    <tr>
        <td>King Welmar’s Castle</td>
        <td>CircleMUD*</td>
        <td>Fairly Easy 15+</td>
        <td>..</td>
    </tr>
    <tr>
        <td>Land of the Goblin</td>
        <td>Maynard of StrangeMUD</td>
        <td>Very Easy 1+</td>
        <td>..</td>
    </tr>
    <tr>
        <td>The High Tower Of Magic</td>
        <td>Skylar of SillyMUD*</td>
        <td>Medium 20+</td>
        <td>..</td>
    </tr>
    <tr>
        <td>The Three Of Swords</td>
        <td>C.A.W. (Curious Area Workshop)</td>
        <td>..</td>
        <td>..</td>
    </tr>
    <tr>
        <td>Miden’Nir</td>
        <td>Copper II, modified by VampLestat of MercMUD*</td>
        <td>..</td>
        <td>..</td>
    </tr>
    <tr>
        <td>The Chessboard</td>
        <td>Exxon of SillyMUD</td>
        <td>Easy 10+</td>
        <td>..</td>
    </tr>
    <tr>
        <td>Mount Moria</td>
        <td>DikuMUD*</td>
        <td>..</td>
        <td>..</td>
    </tr>
    <tr>
        <td>The Great Eastern Desert</td>
        <td>Rorschach</td>
        <td>Medium 20+</td>
        <td>..</td>
    </tr>
    <tr>
        <td>The Drow City</td>
        <td>Rorschach</td>
        <td>Medium 20+</td>
        <td>..</td>
    </tr>
    <tr>
        <td>The City Of Thalos</td>
        <td>Rorschach</td>
        <td>..</td>
        <td>..</td>
    </tr>
    <tr>
        <td>The Great Pyramid</td>
        <td>Andersen of HexOynx*</td>
        <td>..</td>
        <td>..</td>
    </tr>
    <tr>
        <td>New Thalos</td>
        <td>Duke Of SillyMUD*</td>
        <td>..</td>
        <td>..</td>
    </tr>
    <tr>
        <td>The Haon-Dor Forest</td>
        <td>DikuMUD, modified by Derkhil of CircleMUD</td>
        <td>..</td>
        <td>..</td>
    </tr>
    <tr>
        <td>The Orc Enclave</td>
        <td>C.A.W.</td>
        <td>Hard 30+</td>
        <td>..</td>
    </tr>
    <tr>
        <td>Rand’s Tower</td>
        <td>C.A.W.</td>
        <td>..</td>
        <td>..</td>
    </tr>
    <tr>
        <td>The Dwarven Kingdom</td>
        <td>DikuMUD</td>
        <td>..</td>
        <td>..</td>
    </tr>
    <tr>
        <td>The Sewers</td>
        <td>DikuMUD</td>
        <td>Easy 10+</td>
        <td>..</td>
    </tr>
    <tr>
        <td>Arachnos</td>
        <td>Mahatma of HexOynx</td>
        <td>..</td>
        <td>..</td>
    </tr>
    <tr>
        <td>River Island Of Minos</td>
        <td>Mahatma of HexOynx</td>
        <td>Medium 20+</td>
        <td>..</td>
    </tr>
    <tr>
        <td>Redferne’s Residence</td>
        <td>DikuMUD, modified by Cyron of VieMUD</td>
        <td>..</td>
        <td></td>
    </tr>
    <tr>
        <td>Vice Isle</td>
        <td>Questor</td>
        <td>Medium 20+</td>
        <td>..</td>
    </tr>
    <tr>
        <td>Lothlorien</td>
        <td>MaDMaX, mortal of Darklord</td>
        <td>Medium 25+</td>
        <td>..</td>
    </tr>
    <tr>
        <td>The Rainbow to Heaven</td>
        <td>Cain of Darklord</td>
        <td>Very Hard 35+</td>
        <td>..</td>
    </tr>
    <tr>
        <td>Land of Enroth</td>
        <td>Azure of Darklord</td>
        <td>Very Hard 35+</td>
        <td>..</td>
    </tr>
    <tr>
        <td>Empire of Thyatis</td>
        <td>Azure of Darklord</td>
        <td>Fairly Hard 25+</td>
        <td>n;n;n;n;n;w;w;w;open gate;w;w;w;w;w;w;w;w;w;w;w;w;w;n;n;w;w;w;open branches;n;n;n;n;e;e;n;n;n;n</td>
    </tr>
    <tr>
        <td>Ogre Den</td>
        <td>Grif of Darklord</td>
        <td>Hard 30+</td>
        <td>..</td>
    </tr>
    <tr>
        <td>The Shadow Realms</td>
        <td>Grif of Darklord</td>
        <td>Very Hard 35+</td>
        <td>..</td>
    </tr>
    <tr>
        <td>Dragon Sea</td>
        <td>Grif of Darklord</td>
        <td>Hard 30+</td>
        <td>..</td>
    </tr>
    <tr>
        <td>Power Struggle</td>
        <td>Grif of Darklord</td>
        <td>Hard 30+</td>
        <td>..</td>
    </tr>
    <tr>
        <td>The Lost City</td>
        <td>Ben of Darklord</td>
        <td>Fairly Hard 25+</td>
        <td>n;n;n;n;n;w;w;w;w;w;w;w;w;w;n;n;w;n;w;n;n;n;u;n;w;w;n</td>
    </tr>
    <tr>
        <td>Mynris Island</td>
        <td>Mythran of Darklord</td>
        <td>Medium 20+</td>
        <td>..</td>
    </tr>
    <tr>
        <td>The Abyss</td>
        <td>Azure of Darklord</td>
        <td>Medium 20+</td>
        <td>n;e;e;e;s;s;s;e;e;e;e;n;d;s;s;w;w;w;s;s;w;s;w;s;w;s;d;d;d;d;d;d</td>
    </tr>
    <tr>
        <td>Land of Mordor</td>
        <td>Azure of Darklord</td>
        <td>Medium 20+</td>
        <td>n;e;e;e;s;s;s;e;e;e;e;e;e;e;n;n;e;e;e;e;e;e;n;n;n;n;e;e;e;e;s;e;s;e;s;e;s;e;s;e;s;e;e;e;u;e;s;s;s;s;s;s;s
        </td>
    </tr>
    <tr>
        <td>Land of the Ogre</td>
        <td>TigerDude &amp; Azure</td>
        <td>Hard 30+</td>
        <td>..</td>
    </tr>
    <tr>
        <td>Boot Camp + Newbie Zone</td>
        <td>TigerDude of Darklord</td>
        <td>Very Easy 1-15</td>
        <td>..</td>
    </tr>
    <tr>
        <td>The Haunted House</td>
        <td>TigerDude of Darklord</td>
        <td>Medium 20+</td>
        <td>..</td>
    </tr>
    <tr>
        <td>Hero and Demigod Clubs</td>
        <td>TigerDude of Darklord</td>
        <td>43 and 48</td>
        <td>..</td>
    </tr>
    <tr>
        <td>Deluxe Dragonia Arena</td>
        <td>TigerDude of Darklord</td>
        <td>All Levels</td>
        <td>..</td>
    </tr>
    <tr>
        <td>The Fourth Dimension</td>
        <td>TigerDude of Darklord</td>
        <td>Extremely Hard 40+</td>
        <td>..</td>
    </tr>
    <tr>
        <td>Residential Area</td>
        <td>TigerDude of Darklord</td>
        <td>-Not Applicable-</td>
        <td>..</td>
    </tr>
    <tr>
        <td>Forest of Khanjar</td>
        <td>Methem of Alhazi Invasion, modified by TigerDude</td>
        <td>..</td>
        <td></td>
    </tr>
    <tr>
        <td>Team Arena</td>
        <td>Francis of Darklord</td>
        <td>All Levels</td>
        <td>..</td>
    </tr>
    <tr>
        <td>Realm of the Mountain</td>
        <td>Francis of Darklord</td>
        <td>25 ++</td>
        <td>..</td>
    </tr>
    <tr>
        <td>Prehistoric Continent</td>
        <td>Datalore of Darklord</td>
        <td>Very Hard 35+</td>
        <td>n;w;w;w;n;n;n;w;w;w;w;w;w;w;w;w;w;w;w;w;s;w;w;s;s;w;s;w;w;w;n;w;n;n;n;e;e;n;n;n;n</td>
    </tr>
    <tr>
        <td>The Roman Empire</td>
        <td>Datalore of Darklord</td>
        <td>All levels 1-53</td>
        <td>n;w;w;w;s;s;s;s;s;u;s;u;s;d;s;d;s</td>
    </tr>
    <tr>
        <td>Wonderland</td>
        <td>Datalore of Darklord</td>
        <td>Hard 30/35+</td>
        <td>..</td>
    </tr>
    <tr>
        <td>Middle-Earth</td>
        <td>Datalore of Darklord</td>
        <td>All levels 1-53</td>
        <td>..</td>
    </tr>
    <tr>
        <td>Magus’s Lair <img class="emoji" title=":new:" alt=":new:"
                              src="https://assets-cdn.github.com/images/icons/emoji/unicode/1f195.png" height="20"
                              width="20">
        </td>
        <td>Cyrus of Darklord</td>
        <td>40+ group oriented</td>
        <td>..</td>
    </tr>
    <tr>
        <td>Lloth’s Peak</td>
        <td>Sith of Darklord</td>
        <td>40+</td>
        <td>See <a href="https://www.facebook.com/groups/1971833113088195/1976306945974145/">this FB post</a>
        </td>
    </tr>
    </tbody>
</table>
