<?php
declare(strict_types=1);
$this->headTitle('Darklord MUD');
?>

<p><em>Note: not all of these directions have been tested... use with caution!</em></p>
<table>
    <thead>
    <tr>
        <th>Zone</th>
        <th>Author</th>
        <th>Est. Levels</th>
        <th>Directions</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>Limbo</td>
        <td>DikuMud</td>
        <td>Idle</td>
        <td>..</td>
    </tr>
    <tr>
        <td>Tristeza Forgotten</td>
        <td>Mogwai of Darklord</td>
        <td>Hard 30+</td>
        <td>
            n;w;w;w;n;n;n;w;w;w;w;w;w;w;w;w;w;s;s;s;w;s;s;w;w;w;s;w;s;u;u;u;get key;d;d;d;e;e;u;unlock door;open door;n;touch mirror
            <br /><cite>&mdash; Barak from Viking's site</cite>
        </td>
    </tr>
    <tr>
        <td>Eastern Forest</td>
        <td>Mogwai of Darklord</td>
        <td>Hard 30+</td>
        <td>..</td>
    </tr>
    <tr>
        <td>Thistledown</td>
        <td>Mogwai of Darklord</td>
        <td>Hard</td>
        <td>n;n;n;n;n;n;n;n;n;n;n;n;n;n;w;n;w;w;n;n;e;n;n;n;n;n;n;n;n</td>
    </tr>
    <tr>
        <td>Dragonia</td>
        <td>Mogwai of Darklord</td>
        <td>Varies</td>
        <td>..</td>
    </tr>
    <tr>
        <td>Lakeside Park</td>
        <td>Mogwai of Darklord</td>
        <td>Very Easy 1+</td>
        <td>..</td>
    </tr>
    <tr>
        <td>Temple of Syrinx</td>
        <td>Mogwai of Darklord</td>
        <td>Very Hard 35+</td>
        <td>..</td>
    </tr>
    <tr>
        <td>Thonia</td>
        <td>Mogwai of Darklord</td>
        <td>Hard</td>
        <td>..</td>
    </tr>
    <tr>
        <td>Oestgaard</td>
        <td>Foriz of Darklord</td>
        <td>Hard</td>
        <td>..</td>
    </tr>
    <tr>
        <td>Forgotten Fortress</td>
        <td>Foriz of Darklord</td>
        <td>Medium 25+</td>
        <td>
            n;n;n;n;n;e;e;e;e;e;e;e;e;e;e;e;e;e;e;e;e;e;e;e;s;s;s;s;s
            <br /><cite>&mdash; Excalibur from Viking's site</cite>
        </td>
    </tr>
    <tr>
        <td>Sorcerer’s Isle</td>
        <td>Milamber of Darklord</td>
        <td>Easy 10+</td>
        <td>..</td>
    </tr>
    <tr>
        <td>Stonehenge</td>
        <td>Chronos of Darklord</td>
        <td>..</td>
        <td>..</td>
    </tr>
    <tr>
        <td>Highlands</td>
        <td>Mogwai of Darklord</td>
        <td>..</td>
        <td>..</td>
    </tr>
    <tr>
        <td>Dantes’ Limbo</td>
        <td>Addler &amp; Jarnot of Darklord</td>
        <td>Hard 30+</td>
        <td>..</td>
    </tr>
    <tr>
        <td>Valley of War</td>
        <td>Loretian, mortal of Darklord</td>
        <td>Level 8+</td>
        <td>..</td>
    </tr>
    <tr>
        <td>God Complex</td>
        <td>CircleMUD, modified by Datalore of Darklord</td>
        <td>..</td>
        <td>..</td>
    </tr>
    <tr>
        <td>King Welmar’s Castle</td>
        <td>CircleMUD*</td>
        <td>Fairly Easy 15+</td>
        <td>
            n;n;n;n;n;e;e;e;e;e;e;e;n;n
            <br /><cite>&mdash; from Viking's site</cite>
        </td>
    </tr>
    <tr>
        <td>Land of the Goblin</td>
        <td>Maynard of StrangeMUD</td>
        <td>Very Easy 1+</td>
        <td>
            <ul>
                <li>
                    Goblin leader (12+): n;w;w;w;s;s;s;w;s;s;s;s;s;s;e;e;s;s;s;s
                    <br /><cite>&mdash; Silvara from Viking's site</cite>
                </li>
                <li>
                    Goblin zone (1+): n;n;n;n;n;n;n;n;e;u;u;u;e;e;s;e;e
                    <br /><cite>&mdash; Balgrath from Viking's site</cite>
                </li>
            </ul>
        </td>
    </tr>
    <tr>
        <td>The High Tower Of Magic</td>
        <td>Skylar of SillyMUD*</td>
        <td>Medium 20+</td>
        <td>
            n;n;n;n;n;e;e;e;e;e;e;n;n;n;n;n;n;n;n;n;n;e;e;n;n;n;n;n;n;u;w;w;w;w;s;s;s;s;e;e;e;e;n;n;n;n;u;w;w;w;w;s;s;s;s;e;e;e
            <br /><cite>&mdash; Excalibur from Viking's site</cite>
        </td>
    </tr>
    <tr>
        <td>The Three Of Swords</td>
        <td>C.A.W. (Curious Area Workshop)</td>
        <td>..</td>
        <td>..</td>
    </tr>
    <tr>
        <td>Miden’Nir</td>
        <td>Copper II, modified by VampLestat of MercMUD*</td>
        <td>..</td>
        <td>..</td>
    </tr>
    <tr>
        <td>The Chessboard</td>
        <td>Exxon of SillyMUD</td>
        <td>Easy 10+</td>
        <td>..</td>
    </tr>
    <tr>
        <td>Mount Moria</td>
        <td>DikuMUD*</td>
        <td>..</td>
        <td>..</td>
    </tr>
    <tr>
        <td>The Great Eastern Desert</td>
        <td>Rorschach</td>
        <td>Medium 20+</td>
        <td>n;e;e;e;s;s;s;e;e;n;e;e;e;e;u;e;s;e;e</td>
    </tr>
    <tr>
        <td>The Drow City</td>
        <td>Rorschach</td>
        <td>Medium 20+</td>
        <td>..</td>
    </tr>
    <tr>
        <td>The City Of Thalos</td>
        <td>Rorschach</td>
        <td>..</td>
        <td>..</td>
    </tr>
    <tr>
        <td>The Great Pyramid</td>
        <td>Andersen of HexOynx*</td>
        <td>20+</td>
        <td>
            n;e;e;e;s;s;s;e;e;e;e;e;e;e;e;e;e;s;e;s;e;n;u;u;open stones
            <br /><cite>&mdash; Barak from Viking's site</cite>
        </td>
    </tr>
    <tr>
        <td>New Thalos</td>
        <td>Duke Of SillyMUD*</td>
        <td>Good for bstab train?</td>
        <td>
            <ul>
                <li>n;e;e;e;s;s;s;e;e;e;e;e;n;n;n;n;n;e;e;e;e;e;n;e;e;e;e;n;e;e;e</li>
                <li>pick/force open gate</li>
                <li>e</li>
            </ul>
            <br /><cite>&mdash; Laertes from Viking's site</cite>
        </td>
    </tr>
    <tr>
        <td>The Haon-Dor Forest</td>
        <td>DikuMUD, modified by Derkhil of CircleMUD</td>
        <td>..</td>
        <td>..</td>
    </tr>
    <tr>
        <td>The Orc Enclave</td>
        <td>C.A.W.</td>
        <td>Hard 30+</td>
        <td>
            n;w;w;w;n;n;n;w;w;w;w;w;w;w;w;w;w;w;w;w;s;w;w;s;s;w;s;w;s;w;w;w;n;w;n;e;e;e;n;n;w;w
            <br /><cite>&mdash; Barak from Viking's site</cite>
        </td>
    </tr>
    <tr>
        <td>Rand’s Tower</td>
        <td>C.A.W.</td>
        <td>..</td>
        <td>..</td>
    </tr>
    <tr>
        <td>The Dwarven Kingdom</td>
        <td>DikuMUD</td>
        <td>5-15</td>
        <td>
            n;n;n;n;n;e;e;e;e;e;e;d
            <br /><cite>&mdash; from Viking's site</cite>
        </td>
    </tr>
    <tr>
        <td>The Sewers</td>
        <td>DikuMUD</td>
        <td>Easy 10+</td>
        <td>..</td>
    </tr>
    <tr>
        <td>Arachnos</td>
        <td>Mahatma of HexOynx</td>
        <td>20+</td>
        <td>
            n;w;w;w;n;n;n;w;w;w;w;w;w;w;w;w;w;w;w;w;s;w;w;w;u;n;n
            <br /><cite>&mdash; Barak from Viking's site</cite>
        </td>
    </tr>
    <tr>
        <td>River Island Of Minos</td>
        <td>Mahatma of HexOynx</td>
        <td>Medium 20+</td>
        <td>
            n;e;e;e;s;s;w;w;w;w;w;n;w;n;w;s
            <br /><cite>&mdash; Barak from Viking's site</cite>
        </td>
    </tr>
    <tr>
        <td>Redferne’s Residence</td>
        <td>DikuMUD, modified by Cyron of VieMUD</td>
        <td>..</td>
        <td></td>
    </tr>
    <tr>
        <td>Vice Isle</td>
        <td>Questor</td>
        <td>Medium 20+</td>
        <td>
            <ul>
                <li>n;e;n;open door;n</li>
                <li>wait for ship to arrive from dragonia harbour then board ship, then get off at next stop</li>
            </ul>
            <br /><cite>&mdash; Barak from Viking's site</cite>
        </td>
    </tr>
    <tr>
        <td>Lothlorien</td>
        <td>MaDMaX, mortal of Darklord</td>
        <td>Medium 25+</td>
        <td>
            <ul>
                <li>n;e;n;open door;n</li>
                <li>wait for ship to arrive from dragonia harbour then board ship, then get off at the second stop</li>
                <li>e;e;e;e;e;s;s;s;s;s;s;s;s;s;s;w;w;w;w;s;s;s;s;s;s;e;e;e;n;open gate</li>
            </ul>
            <br /><cite>&mdash; Barak from Viking's site</cite>
        </td>
    </tr>
    <tr>
        <td>The Rainbow to Heaven</td>
        <td>Cain of Darklord</td>
        <td>Very Hard 35+</td>
        <td>
            <ul>
                <li>n;w;w;w;n;n;n;w;w;w;w;w;w;w;w;w;w;w;w;w;s;w;w;s;s;w;s;w;s;w;w;w;n;w;n;n;n;e;e</li>
                <li>find jojo; give him 10k gold</li>
                <li>u;u;w;u;w;u;w;u;w;u;w</li>
                <li>watch out for elven assasin aggro + hidden</li>
                <li>w</li>
            </ul>
            <br /><cite>&mdash; Barak from Viking's site</cite>
        </td>
    </tr>
    <tr>
        <td>Land of Enroth</td>
        <td>Azure of Darklord</td>
        <td>Very Hard 35+</td>
        <td>..</td>
    </tr>
    <tr>
        <td>Empire of Thyatis</td>
        <td>Azure of Darklord</td>
        <td>Fairly Hard 25+</td>
        <td>n;n;n;n;n;w;w;w;open gate;w;w;w;w;w;w;w;w;w;w;w;w;w;n;n;w;w;w;open branches;n;n;n;n;e;e;n;n;n;n</td>
    </tr>
    <tr>
        <td>Ogre Den</td>
        <td>Grif of Darklord</td>
        <td>Hard 30+</td>
        <td>..</td>
    </tr>
    <tr>
        <td>The Shadow Realms</td>
        <td>Grif of Darklord</td>
        <td>Very Hard 35+</td>
        <td>..</td>
    </tr>
    <tr>
        <td>Dragon Sea</td>
        <td>Grif of Darklord</td>
        <td>Hard 30+</td>
        <td>..</td>
    </tr>
    <tr>
        <td>Power Struggle</td>
        <td>Grif of Darklord</td>
        <td>Hard 30+</td>
        <td>
            n;e;e;e;s;s;e;e;e;e;n;n;n;n;n;n;n;e;e;e;e;e;e;e;e;e;e;open grating;e;e;e;e;open grating;e;e;s;s;e;s;e;s;s;w;s;s;w;s;e
            <br /><cite>&mdash; Barak from Viking's site</cite>
        </td>
    </tr>
    <tr>
        <td>The Lost City</td>
        <td>Ben of Darklord</td>
        <td>Fairly Hard 25+</td>
        <td>n;n;n;n;n;w;w;w;w;w;w;w;w;w;n;n;w;n;w;n;n;n;u;n;w;w;n</td>
    </tr>
    <tr>
        <td>Mynris Island</td>
        <td>Mythran of Darklord</td>
        <td>Medium 20+ / 30+</td>
        <td>
            <ul>
                <li>n;e;n;open door;n</li>
                <li>wait for ship to arrive from dragonia harbour then board ship, then get off at the second stop</li>
            </ul>
            <br /><cite>&mdash; Barak from Viking's site</cite>
        </td>
    </tr>
    <tr>
        <td>The Abyss</td>
        <td>Azure of Darklord</td>
        <td>Medium 20+</td>
        <td>n;e;e;e;s;s;s;e;e;e;e;e;d;s;s;w;w;w;s;s;w;s;w;s;w;s;d;d;d;d;d;d (updated)</td>
    </tr>
    <tr>
        <td>Land of Mordor</td>
        <td>Azure of Darklord</td>
        <td>Medium 20+</td>
        <td>
            <ul>
                <li>n;e;e;e;s;s;s;e;e;e;e;e;e;e;n;n;e;e;e;e;e;e;n;n;n;n;e;e;e;e;s;e;s;e;s;e;s;e;s;e;s;e;e;e;u;e;s;s;s;s;s;s;s</li>
                <li>
                    n;e;e;e;s;s;s;e;e;e;e;e;e;e;n;e;e;e;e;e;n;n;e;e;e;e;e;n;e;n;e;n;e;e;e;e;u;e;e;s;s;s;s;s;w;s;s;e;d;e;d;e;d;e;e;e;open gates;e;e;e;e;e
                    <br /><cite>&mdash; "Dest from Cloak Figure" from Viking's site</cite>
                </li>
            </ul>
        </td>
    </tr>
    <tr>
        <td>Land of the Ogre</td>
        <td>TigerDude &amp; Azure</td>
        <td>Hard 30+</td>
        <td>
            n,w,w,w,n,n,n,w,w,w,w,w,w,w,w,w,w,w,w,w,s,w,w,s,s,w,s,w,s,w,w,w,n,w,n,e,e,e,n,n,w,w,n,w,n,w,n
            <br /><cite>&mdash; Barak from Viking's site</cite>
        </td>
    </tr>
    <tr>
        <td>Boot Camp + Newbie Zone</td>
        <td>TigerDude of Darklord</td>
        <td>Very Easy 1-15</td>
        <td>
            n;n;n;n;n;n;n;n;e;u;u;u
            <br /><cite>&mdash; from Viking's site</cite>
        </td>
    </tr>
    <tr>
        <td>The Haunted House</td>
        <td>TigerDude of Darklord</td>
        <td>Medium 20+</td>
        <td>..</td>
    </tr>
    <tr>
        <td>Hero and Demigod Clubs</td>
        <td>TigerDude of Darklord</td>
        <td>43 and 48</td>
        <td>..</td>
    </tr>
    <tr>
        <td>Deluxe Dragonia Arena</td>
        <td>TigerDude of Darklord</td>
        <td>All Levels</td>
        <td>..</td>
    </tr>
    <tr>
        <td>The Fourth Dimension</td>
        <td>TigerDude of Darklord</td>
        <td>Extremely Hard 40+</td>
        <td>
            n;w;w;w;s;s;s;w;s;s;s;e;e;e;enter cave;e;e;e;n;e;s;s;enter portal;s;w;s;e;e
            <br /><cite>&mdash; MVP from Viking's site</cite>
        </td>
    </tr>
    <tr>
        <td>Residential Area</td>
        <td>TigerDude of Darklord</td>
        <td>-Not Applicable-</td>
        <td>..</td>
    </tr>
    <tr>
        <td>Forest of Khanjar</td>
        <td>Methem of Alhazi Invasion, modified by TigerDude</td>
        <td>5+</td>
        <td>
            n;w;w;w;s;s;s;w;s;w;s;s;w;w;s;w;s;e;e;e;e
            <br /><cite>&mdash; Excalibur from Viking's site</cite>
        </td>
    </tr>
    <tr>
        <td>Team Arena</td>
        <td>Francis of Darklord</td>
        <td>All Levels</td>
        <td>..</td>
    </tr>
    <tr>
        <td>Realm of the Mountain</td>
        <td>Francis of Darklord</td>
        <td>25 ++</td>
        <td>..</td>
    </tr>
    <tr>
        <td>Prehistoric Continent</td>
        <td>Datalore of Darklord</td>
        <td>Very Hard 35+</td>
        <td>n;w;w;w;n;n;n;w;w;w;w;w;w;w;w;w;w;w;w;w;s;w;w;s;s;w;s;w;w;w;n;w;n;n;n;e;e;n;n;n;n</td>
    </tr>
    <tr>
        <td>The Roman Empire</td>
        <td>Datalore of Darklord</td>
        <td>All levels 1-53</td>
        <td>
            <ul>
                <li>
                    Via Sacra: n;w;w;w;s;s;s;s;s;u;s;u;s;d;s;d;s
                </li>
                <li>
                    Legionary Fortress (25+): n;w;w;w;s;s;s;s;s;u;s;u;s;d;s;d;s;w;w;w;w;w;w;w;w;u;w;u;w;d;w;d;w
                    <br /><cite>&mdash; from Viking's site</cite>
                </li>
            </ul>
        </td>
    </tr>
    <tr>
        <td>Wonderland</td>
        <td>Datalore of Darklord</td>
        <td>Hard 30/35+</td>
        <td>
            n;w;w;w;n;n;n;w;w;w;w;w;w;s;s;w;w;w;w;follow rabbit
            <br /><cite>&mdash; Barak from Viking's site</cite>
        </td>
    </tr>
    <tr>
        <td>Middle-Earth</td>
        <td>Datalore of Darklord</td>
        <td>All levels 1-53</td>
        <td>..</td>
    </tr>
    <tr>
        <td>Magus’s Lair <img class="emoji" title=":new:" alt=":new:"
                              src="https://assets-cdn.github.com/images/icons/emoji/unicode/1f195.png" height="20"
                              width="20">
        </td>
        <td>Cyrus of Darklord</td>
        <td>40+ group oriented</td>
        <td>..</td>
    </tr>
    <tr>
        <td>Lloth’s Peak</td>
        <td>Sith of Darklord</td>
        <td>40+</td>
        <td>See <a href="https://www.facebook.com/groups/1971833113088195/1976306945974145/">this FB post</a>
        </td>
    </tr>
    <tr>
        <td>Ben's Zone</td>
        <td></td>
        <td>30+</td>
        <td>
            n;n;n;n;n;w;w;w;w;w;w;w;w;w;n;n;w;n;e;n;n;u;u;u;enter hole;d;n;w;w;n;n;enter gate
            <br /><cite>&mdash; Datalore from Viking's site</cite>
        </td>
    </tr>
    <tr>
        <td>Circus Maximus</td>
        <td></td>
        <td>40+</td>
        <td>
            n;w;w;w;s;s;s;s;s;u;s;u;s;d;s;d;s;w;w;s;s;u;s;u;s;d;s;d;s;s
            <br /><cite>&mdash; Teferi from Viking's site</cite>
        </td>
    </tr>
    <tr>
        <td>Grand Knight Paladine</td>
        <td></td>
        <td>25+</td>
        <td>
            n;w;w;w;s;s;s;w;s;s;s;u;u;u;u;u
            <br /><cite>&mdash; Pirate from Viking's site</cite>
        </td>
    </tr>
    <tr>
        <td>Hell</td>
        <td></td>
        <td>32+</td>
        <td>
            n;e;e;e;s;s;s;e;e;e;n;d;s;e;s;e;s;s;e;s;e
            <br /><cite>&mdash; Barak from Viking's site</cite>
        </td>
    </tr>
    <tr>
        <td>Hobbiton</td>
        <td></td>
        <td>15+</td>
        <td>
            n;w;w;w;s;s;s;w;s;s;s;s;s;s;e;e;e;e;e
            <br /><cite>&mdash; Cough from Viking's site</cite>
        </td>
    </tr>
    <tr>
        <td>Isle of the Vaere</td>
        <td></td>
        <td>1+</td>
        <td>
            n;e;n;open door;n
            <br /><cite>&mdash; Barak from Viking's site</cite>
        </td>
    </tr>
    <tr>
        <td>Mercaptans Bar</td>
        <td></td>
        <td>"AA grads O" (??)</td>
        <td>
            n;n;n;n;n;w;w;w;w;w;w;w;w;w;w;w;w;w;w;w;w;s;s;e;s;w;s;w;w;s;w;n;w;w;w;n;w;n;n;n;e;e;n;n;n;w;n
            <br /><cite>&mdash; Destruction from Viking's site</cite>
        </td>
    </tr>
    <tr>
        <td>New Dwarven Realms</td>
        <td></td>
        <td>20-45</td>
        <td>
            n;n;n;n;n;e;e;e;e;e;e;northeast
            <br /><cite>&mdash; Paul from Viking's site</cite>
        </td>
    </tr>
    <tr>
        <td>Snowball Area</td>
        <td></td>
        <td>22+</td>
        <td>
            n;e;e;e;n;n;n;e;e;e;e;e;e;e;e;e;e;e;e;e;e;e;e;e;e;e;e;e;e;e;n;n;n;n;n;e;e;e;e;e;e;e;e;e;e;e;e;e;e;n;n;e;s;s;e;e;s;n;enter slope;e;n;e;n;n;e;u;u
            <br /><cite>&mdash; Blizz from Viking's site</cite>
        </td>
    </tr>
    <tr>
        <td>The Well</td>
        <td></td>
        <td>20+</td>
        <td>
            n;n;n;n;n;n;n;n;w;w;n;e;n;n;n;w;w;w;n;talk man;enter well
            <br /><cite>&mdash; Hector from Viking's site</cite>
        </td>
    </tr>
    <tr>
        <td>Village</td>
        <td></td>
        <td>25+ (must have boat or water walk)</td>
        <td>
            n;n;n;n;n;e;e;e;e;e;e;e;e;e;e;e;e;e;e;e;e;e;e;e;e;e;e;e;e;e;n;n;n;n;n;e;e;e;e;e;e;e
            <br /><cite>&mdash; Destruction/Goldmoon from Viking's site</cite>
        </td>
    </tr>
    <tr>
        <td>Volcano</td>
        <td></td>
        <td>35+</td>
        <td>
            <ul>
                <li>n;e;n;open door;n</li>
                <li>wait for ship to arrive from dragonia harbour then board ship, then get off at the second stop</li>
                <li>w;n;n;n;n;n;n;n;n;n;n;n;n;n;n;n;n;n;w;w;w;w;n;n;n;n;n;n;n;n;n;n</li>
            </ul>
            <br /><cite>&mdash; tucan from Viking's site</cite>
        </td>
    </tr>
    </tbody>
</table>

<h2>Guilds</h2>

<table>
    <thead>
    <tr>
        <th>Class</th>
        <th>Directions</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>Cleric</td>
        <td>
            n;w;w;s;u
            <br /><cite>&mdash; Dak from Viking's site</cite>
        </td>
    </tr>
    <tr>
        <td>Mage</td>
        <td>
            <ul>
                <li><code>cast portal self</code>, or</li>
                <li>n;e;n;open door;n;n;n;n;e;n then type <code>verify</code></li>
            </ul>
            <br /><cite>&mdash; MaDMaX from Viking's site</cite>
        </td>
    </tr>
    <tr>
        <td>Templar</td>
        <td>
            n;e;e;e;n;n;n;e;e;e;n;n;n;n;n;e;e;s;s;s
            <br /><cite>&mdash; MaDMaX from Viking's site</cite>
        </td>
    </tr>
    <tr>
        <td>Thief</td>
        <td>
            n;n;n;n;n;e;e;e;open gate;e;e;e;n;n;e;e;d;e;e;e;e;s;s;s;w;s;w;s;e;e;s;s;e;n;e;s;s;e;n;e;d;s;s
        </td>
    </tr>
    <tr>
        <td>Warror</td>
        <td>
            n;w;w;w;s;s;s;w;s;e;e;e;e;e;u;e;s;d
            <br /><cite>&mdash; MaDMaX from Viking's site</cite>
        </td>
    </tr>
    </tbody>
</table>

<h2>Eastern Desert 2.0 update</h2>
<img src="/images/map-eastern-desert.jpg" height="500" class="pull-left with-padding" />
<ul>
    <li>The Desert Map has been redone, as posted above. Room 28 is the beginning or Rome and 39 is Old Thalos. Rooms 95 and 99 will lead to future zones.</li>
    <li>A magical meteorite has crashed into the desert and created a great deal of chaos. New monsters appropriate for levels 25-35 will roam around, though travelers to Oestgaard need not worry about getting aggro killed on the way to town.</li>
    <li>The Brass Dragon has been tweaked and will hold new appropriate loot. Please be careful, as his cave is <code>!MAGIC</code>.</li>
    <li><cite>-- Cyrus</cite> (<a href="https://www.facebook.com/groups/1971833113088195/permalink/1989826624622177/">source</a>)</li>
</ul>
<div class="clearfix"></div>

<h2>Pyramid 2.0 update</h2>
<img src="/images/map-pyramid.jpg" height="500" class="pull-left with-padding" />
<ul>
    <li><cite>-- Cyrus</cite> (<a href="https://www.facebook.com/groups/1971833113088195/permalink/1990623157875857/">source</a>)</li>
</ul>
<div class="clearfix"></div>
