language: php
sudo: false

php:
  - 7.1

before_script:
  - composer install --prefer-dist --optimize-autoloader

script:
  - vendor/bin/php-cs-fixer fix --dry-run --config=.php_cs.php ;
  - vendor/bin/phpunit --coverage-text --coverage-clover=clover.xml --colors

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover clover.xml
