version: '3'

services:
  darklord-postgres:
    build: docker/postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=darklord
    ports:
      - 5432:5432

  darklord-php-fpm:
    build: docker/php-fpm
    environment:
      - DATABASE_URL=postgres://postgres:postgres@localhost/darklord
    volumes:
      - .:/app
    depends_on:
      - darklord-postgres
    links:
      - darklord-postgres

  darklord-nginx:
    build: docker/nginx
    volumes:
      - .:/app
    depends_on:
      - darklord-php-fpm
    links:
      - darklord-php-fpm
    ports:
      - 8080:8080

